### ISSUE TITLE
Non array, non string values

### ISSUE THREAD

**Issue by leobalter** [hax/proposal-index-from-end#2]
What `^1` means in objects that are not array or string values? 

```js
// Ordinary
({})[^1];

// Array-like objects
({length: 5, 4: 'foo'})[^1];

// Proxied Arrays
new Proxy([,,7], {
  get(t, p) {
    return t[p]; // what p is?
  }
})[^1];
```

There may be a problematic here, seen in the proxy example where a `^0` token would need to capture the length size of the target object before operating the expected `[[Get]]` operation.

From what I see in the explainer, it actually does that already, object's `length` is captured before getting the property. It's a bit weird as it causes 2 trap calls in the proxy.

```js
new Proxy([,,7], {
  get(t, p) {
    console.log(p);
    return t[p]; // what p is?
  }
})[^1];

// Logs:
// "length"
// "2"
```

To add some _fun_:

```js
var rev = Proxy.revocable([,,7], {
  get(t, p) {
    console.log(p);
    rev.revoke();
    return t[p];
  }
});

rev.proxy[^1];

// Logs: "length"
// throws TypeError

// Similar to 
// rev.proxy.length; rev.proxy[2];
```

**Comment by hax** [comment]
> What ^0 means in objects that are not array or string values?

For all ArrayLike, `a[^i]` always mean `a[a.length - i]`, it leave the question that what the behavior for non ArrayLike, aka. no `length` property (or have the `length` property coerce to `NaN`), I already create a issue for that: #1 . So would u ok that I close this issue as duplicated?

> object's length is captured before getting the property. 

Yes.

> It's a bit weird as it causes 2 trap calls in the proxy.

Actually it's what must happen, whether we use `a[^i]` or `a.at(-i)` or just write `a[a.length - 1]` :-)

**Comment by leobalter** [comment]
I'm sorry I wrote `^0` but I meant `^1` representing the `length - 1`. 

> Actually it's what must happen, whether we use `a[^i]` or `a.at(-i)` or just write `a[a.length - 1]` :-)

This is the actual question I meant.

When we do `a[a.length - 1]`, we have an explicit syntax showing both operations. `a.at(-i)` is also a method which I can expect multiple operations. The `a[^i]` leaves it implicit. It's not a dealbraker at all, but something I'd like to see expressed in the explainer. At some point this would eventually become clearly represented by spec text anyway.

**Comment by hax** [comment]
> but something I'd like to see expressed in the explainer.

Good point. I add a [section](https://github.com/hax/proposal-index-from-end/blob/main/README.md#semantics) to explain that.

**Comment by hax** [comment]
I think this issue was solved. Feel free to reopen if there is still something missed.
